### ISSUE TITLE
This module appears to be failing tests due to missing MONKEY-SEE-NO-EVAL

### ISSUE THREAD

**Issue by cschwenz** [perl6-community-modules/yaml-pm6#3]
% zef install YAML
    ===> Searching for: YAML
    ===> Testing: YAML
    === Test Dumping Perl 6 Data Objects to YAML ===
    ===SORRY!=== Error while compiling /Users/cal/.zef/store/yaml-pm6.git/69c454f2f0c95cabf2f18df8759a2c8b29d1cdb3/t/Bridge.pm (t::Bridge)
    EVAL is a very dangerous function!!! (use the MONKEY-SEE-NO-EVAL pragma to override this error,
    but only if you're VERY sure your data contains no injection attacks)
    at /Users/cal/.zef/store/yaml-pm6.git/69c454f2f0c95cabf2f18df8759a2c8b29d1cdb3/t/Bridge.pm (t::Bridge):8
    ------>     return EVAL $this.value⏏;
    
      in method _transform_modules at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A182E9F733D1C685F9F4F998B3332FE5B493FEBB (TestML::Runner) line 225
      in method transform_modules at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A182E9F733D1C685F9F4F998B3332FE5B493FEBB (TestML::Runner) line 87
      in method get_transform_function at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A182E9F733D1C685F9F4F998B3332FE5B493FEBB (TestML::Runner) line 201
      in method evaluate_expression at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A182E9F733D1C685F9F4F998B3332FE5B493FEBB (TestML::Runner) line 167
      in block  at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A182E9F733D1C685F9F4F998B3332FE5B493FEBB (TestML::Runner) line 105
      in method run at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A182E9F733D1C685F9F4F998B3332FE5B493FEBB (TestML::Runner) line 100
      in block <unit> at t/dump.t line 5
    
    t/dump.t ..... All 13 subtests passed
    === Failing Tests For People to Hack On ===
    ===SORRY!=== Error while compiling /Users/cal/.zef/store/yaml-pm6.git/69c454f2f0c95cabf2f18df8759a2c8b29d1cdb3/t/Bridge.pm (t::Bridge)
    EVAL is a very dangerous function!!! (use the MONKEY-SEE-NO-EVAL pragma to override this error,
    but only if you're VERY sure your data contains no injection attacks)
    at /Users/cal/.zef/store/yaml-pm6.git/69c454f2f0c95cabf2f18df8759a2c8b29d1cdb3/t/Bridge.pm (t::Bridge):8
    ------>     return EVAL $this.value⏏;
    
      in method _transform_modules at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A182E9F733D1C685F9F4F998B3332FE5B493FEBB (TestML::Runner) line 225
      in method transform_modules at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A182E9F733D1C685F9F4F998B3332FE5B493FEBB (TestML::Runner) line 87
      in method get_transform_function at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A182E9F733D1C685F9F4F998B3332FE5B493FEBB (TestML::Runner) line 201
      in method evaluate_expression at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A182E9F733D1C685F9F4F998B3332FE5B493FEBB (TestML::Runner) line 167
      in block  at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A182E9F733D1C685F9F4F998B3332FE5B493FEBB (TestML::Runner) line 105
      in method run at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A182E9F733D1C685F9F4F998B3332FE5B493FEBB (TestML::Runner) line 100
      in block <unit> at t/fail.t line 5
    
    t/fail.t ..... All 1 subtests passed
    === Various String Quoting ===
    ===SORRY!=== Error while compiling /Users/cal/.zef/store/yaml-pm6.git/69c454f2f0c95cabf2f18df8759a2c8b29d1cdb3/t/Bridge.pm (t::Bridge)
    EVAL is a very dangerous function!!! (use the MONKEY-SEE-NO-EVAL pragma to override this error,
    but only if you're VERY sure your data contains no injection attacks)
    at /Users/cal/.zef/store/yaml-pm6.git/69c454f2f0c95cabf2f18df8759a2c8b29d1cdb3/t/Bridge.pm (t::Bridge):8
    ------>     return EVAL $this.value⏏;
    
      in method _transform_modules at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A182E9F733D1C685F9F4F998B3332FE5B493FEBB (TestML::Runner) line 225
      in method transform_modules at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A182E9F733D1C685F9F4F998B3332FE5B493FEBB (TestML::Runner) line 87
      in method get_transform_function at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A182E9F733D1C685F9F4F998B3332FE5B493FEBB (TestML::Runner) line 201
      in method evaluate_expression at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A182E9F733D1C685F9F4F998B3332FE5B493FEBB (TestML::Runner) line 167
      in block  at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A182E9F733D1C685F9F4F998B3332FE5B493FEBB (TestML::Runner) line 105
      in method run at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A182E9F733D1C685F9F4F998B3332FE5B493FEBB (TestML::Runner) line 100
      in block <unit> at t/strings.t line 5
    
    t/strings.t .. All 3 subtests passed
    All tests successful.
    
    Test Summary Report
    -------------------
    t/dump.t  (Wstat: 0 Tests: 0 Failed: 0)
      Parse errors: Bad plan.  You planned 13 tests but ran 0.
    t/fail.t  (Wstat: 0 Tests: 0 Failed: 0)
      Parse errors: Bad plan.  You planned 1 tests but ran 0.
    t/strings.t (Wstat: 0 Tests: 0 Failed: 0)
      Parse errors: Bad plan.  You planned 3 tests but ran 0.
    Files=3, Tests=0,  3 wallclock secs
    Result: FAILED
    ===> Testing [FAIL]: YAML
    Aborting due to test failure: YAML (use --force to override)
      in code  at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 306
      in method test at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 285
      in code  at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 457
      in sub  at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 454
      in method install at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 560
      in sub MAIN at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/sources/A9948E7371E0EB9AFDF1EEEB07B52A1B75537C31 (Zef::CLI) line 123
      in block <unit> at /usr/local/Cellar/rakudo-star/2017.01/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E line 1
    
    zef install YAML  14.73s user 0.85s system 100% cpu 15.516 total
    % perl6 --version
    This is Rakudo version 2017.01 built on MoarVM version 2017.01
    implementing Perl 6.c.
    %

**Comment by zoffixznet** [comment]
Fixed this one. Thanks.
